//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.01 at 03:38:33 PM IST 
//


package pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Report.Detail }
     * 
     */
    public Report.Detail createReportDetail() {
        return new Report.Detail();
    }

    /**
     * Create an instance of {@link Report.Detail.InvoiceSummary }
     * 
     */
    public Report.Detail.InvoiceSummary createReportDetailInvoiceSummary() {
        return new Report.Detail.InvoiceSummary();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper }
     * 
     */
    public Report.Detail.CustomerWrapper createReportDetailCustomerWrapper() {
        return new Report.Detail.CustomerWrapper();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerTotal }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerTotal createReportDetailCustomerWrapperCustomerTotal() {
        return new Report.Detail.CustomerWrapper.CustomerTotal();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.TransactionWrapper }
     * 
     */
    public Report.Detail.CustomerWrapper.TransactionWrapper createReportDetailCustomerWrapperTransactionWrapper() {
        return new Report.Detail.CustomerWrapper.TransactionWrapper();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.TransactionWrapper.CustomerTransactions }
     * 
     */
    public Report.Detail.CustomerWrapper.TransactionWrapper.CustomerTransactions createReportDetailCustomerWrapperTransactionWrapperCustomerTransactions() {
        return new Report.Detail.CustomerWrapper.TransactionWrapper.CustomerTransactions();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader createReportDetailCustomerWrapperCustomerHeader() {
        return new Report.Detail.CustomerWrapper.CustomerHeader();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails createReportDetailCustomerWrapperCustomerHeaderCustomerDetails() {
        return new Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails();
    }

    /**
     * Create an instance of {@link Report.Detail.TransactionTotals }
     * 
     */
    public Report.Detail.TransactionTotals createReportDetailTransactionTotals() {
        return new Report.Detail.TransactionTotals();
    }

    /**
     * Create an instance of {@link SkipOne }
     * 
     */
    public SkipOne createSkipOne() {
        return new SkipOne();
    }

    /**
     * Create an instance of {@link Report.ReportInfo }
     * 
     */
    public Report.ReportInfo createReportReportInfo() {
        return new Report.ReportInfo();
    }

    /**
     * Create an instance of {@link Report.PageHeader }
     * 
     */
    public Report.PageHeader createReportPageHeader() {
        return new Report.PageHeader();
    }

    /**
     * Create an instance of {@link Report.SoftPage }
     * 
     */
    public Report.SoftPage createReportSoftPage() {
        return new Report.SoftPage();
    }

    /**
     * Create an instance of {@link Report.Detail.SummaryHeader }
     * 
     */
    public Report.Detail.SummaryHeader createReportDetailSummaryHeader() {
        return new Report.Detail.SummaryHeader();
    }

    /**
     * Create an instance of {@link Report.Detail.SummaryDetails }
     * 
     */
    public Report.Detail.SummaryDetails createReportDetailSummaryDetails() {
        return new Report.Detail.SummaryDetails();
    }

    /**
     * Create an instance of {@link Report.Detail.SummaryTotal }
     * 
     */
    public Report.Detail.SummaryTotal createReportDetailSummaryTotal() {
        return new Report.Detail.SummaryTotal();
    }

    /**
     * Create an instance of {@link Report.Detail.AgeingSummaryHeader }
     * 
     */
    public Report.Detail.AgeingSummaryHeader createReportDetailAgeingSummaryHeader() {
        return new Report.Detail.AgeingSummaryHeader();
    }

    /**
     * Create an instance of {@link Report.Detail.AgeingSummaryDetail }
     * 
     */
    public Report.Detail.AgeingSummaryDetail createReportDetailAgeingSummaryDetail() {
        return new Report.Detail.AgeingSummaryDetail();
    }

    /**
     * Create an instance of {@link Report.Detail.AgeingSummaryTotals }
     * 
     */
    public Report.Detail.AgeingSummaryTotals createReportDetailAgeingSummaryTotals() {
        return new Report.Detail.AgeingSummaryTotals();
    }

    /**
     * Create an instance of {@link Report.Detail.ReportGrandTotals }
     * 
     */
    public Report.Detail.ReportGrandTotals createReportDetailReportGrandTotals() {
        return new Report.Detail.ReportGrandTotals();
    }

    /**
     * Create an instance of {@link Report.Detail.ReportOptions }
     * 
     */
    public Report.Detail.ReportOptions createReportDetailReportOptions() {
        return new Report.Detail.ReportOptions();
    }

    /**
     * Create an instance of {@link Report.Detail.ReportFinish }
     * 
     */
    public Report.Detail.ReportFinish createReportDetailReportFinish() {
        return new Report.Detail.ReportFinish();
    }

    /**
     * Create an instance of {@link Report.Detail.InvoiceSummary.InvAgeingSummaryHeader }
     * 
     */
    public Report.Detail.InvoiceSummary.InvAgeingSummaryHeader createReportDetailInvoiceSummaryInvAgeingSummaryHeader() {
        return new Report.Detail.InvoiceSummary.InvAgeingSummaryHeader();
    }

    /**
     * Create an instance of {@link Report.Detail.InvoiceSummary.InvAgeingSummaryDetail }
     * 
     */
    public Report.Detail.InvoiceSummary.InvAgeingSummaryDetail createReportDetailInvoiceSummaryInvAgeingSummaryDetail() {
        return new Report.Detail.InvoiceSummary.InvAgeingSummaryDetail();
    }

    /**
     * Create an instance of {@link Report.Detail.InvoiceSummary.InvAgeingSummaryTotal }
     * 
     */
    public Report.Detail.InvoiceSummary.InvAgeingSummaryTotal createReportDetailInvoiceSummaryInvAgeingSummaryTotal() {
        return new Report.Detail.InvoiceSummary.InvAgeingSummaryTotal();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.AgeingDetails }
     * 
     */
    public Report.Detail.CustomerWrapper.AgeingDetails createReportDetailCustomerWrapperAgeingDetails() {
        return new Report.Detail.CustomerWrapper.AgeingDetails();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerTotal.CustomerTransTotal }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerTotal.CustomerTransTotal createReportDetailCustomerWrapperCustomerTotalCustomerTransTotal() {
        return new Report.Detail.CustomerWrapper.CustomerTotal.CustomerTransTotal();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerTotal.AccountTotal }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerTotal.AccountTotal createReportDetailCustomerWrapperCustomerTotalAccountTotal() {
        return new Report.Detail.CustomerWrapper.CustomerTotal.AccountTotal();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.TransactionWrapper.CustomerTransactions.Transactions }
     * 
     */
    public Report.Detail.CustomerWrapper.TransactionWrapper.CustomerTransactions.Transactions createReportDetailCustomerWrapperTransactionWrapperCustomerTransactionsTransactions() {
        return new Report.Detail.CustomerWrapper.TransactionWrapper.CustomerTransactions.Transactions();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader.CustomerWithTrans }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader.CustomerWithTrans createReportDetailCustomerWrapperCustomerHeaderCustomerWithTrans() {
        return new Report.Detail.CustomerWrapper.CustomerHeader.CustomerWithTrans();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails1 }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails1 createReportDetailCustomerWrapperCustomerHeaderCustomerDetailsCustomerDetails1() {
        return new Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails1();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails2 }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails2 createReportDetailCustomerWrapperCustomerHeaderCustomerDetailsCustomerDetails2() {
        return new Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails2();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails3 }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails3 createReportDetailCustomerWrapperCustomerHeaderCustomerDetailsCustomerDetails3() {
        return new Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerDetails3();
    }

    /**
     * Create an instance of {@link Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerNotes }
     * 
     */
    public Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerNotes createReportDetailCustomerWrapperCustomerHeaderCustomerDetailsCustomerNotes() {
        return new Report.Detail.CustomerWrapper.CustomerHeader.CustomerDetails.CustomerNotes();
    }

    /**
     * Create an instance of {@link Report.Detail.TransactionTotals.PrintedTransactionTotal }
     * 
     */
    public Report.Detail.TransactionTotals.PrintedTransactionTotal createReportDetailTransactionTotalsPrintedTransactionTotal() {
        return new Report.Detail.TransactionTotals.PrintedTransactionTotal();
    }

    /**
     * Create an instance of {@link Report.Detail.TransactionTotals.TransactionGrandTotals }
     * 
     */
    public Report.Detail.TransactionTotals.TransactionGrandTotals createReportDetailTransactionTotalsTransactionGrandTotals() {
        return new Report.Detail.TransactionTotals.TransactionGrandTotals();
    }

}
